/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common';

export interface AlphaHomoraV1PriceFeedInterface extends utils.Interface {
  functions: {
    'calcUnderlyingValues(address,uint256)': FunctionFragment;
    'getIbethToken()': FunctionFragment;
    'getWethToken()': FunctionFragment;
    'isSupportedAsset(address)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'calcUnderlyingValues'
      | 'getIbethToken'
      | 'getWethToken'
      | 'isSupportedAsset',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'calcUnderlyingValues',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: 'getIbethToken',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getWethToken',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'isSupportedAsset',
    values: [PromiseOrValue<string>],
  ): string;

  decodeFunctionResult(
    functionFragment: 'calcUnderlyingValues',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getIbethToken',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getWethToken',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isSupportedAsset',
    data: BytesLike,
  ): Result;

  events: {};
}

export interface AlphaHomoraV1PriceFeed extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AlphaHomoraV1PriceFeedInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     * Converts a given amount of a derivative to its underlying asset values
     * @param _derivative The derivative to convert
     * @param _derivativeAmount The amount of the derivative to convert
     */
    calcUnderlyingValues(
      _derivative: PromiseOrValue<string>,
      _derivativeAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    /**
     * Gets the `IBETH_TOKEN` variable
     */
    getIbethToken(
      overrides?: CallOverrides,
    ): Promise<[string] & { ibethToken_: string }>;

    /**
     * Gets the `WETH_TOKEN` variable
     */
    getWethToken(
      overrides?: CallOverrides,
    ): Promise<[string] & { wethToken_: string }>;

    /**
     * Checks if an asset is supported by the price feed
     * @param _asset The asset to check
     */
    isSupportedAsset(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean] & { isSupported_: boolean }>;
  };

  /**
   * Converts a given amount of a derivative to its underlying asset values
   * @param _derivative The derivative to convert
   * @param _derivativeAmount The amount of the derivative to convert
   */
  calcUnderlyingValues(
    _derivative: PromiseOrValue<string>,
    _derivativeAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  /**
   * Gets the `IBETH_TOKEN` variable
   */
  getIbethToken(overrides?: CallOverrides): Promise<string>;

  /**
   * Gets the `WETH_TOKEN` variable
   */
  getWethToken(overrides?: CallOverrides): Promise<string>;

  /**
   * Checks if an asset is supported by the price feed
   * @param _asset The asset to check
   */
  isSupportedAsset(
    _asset: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  callStatic: {
    /**
     * Converts a given amount of a derivative to its underlying asset values
     * @param _derivative The derivative to convert
     * @param _derivativeAmount The amount of the derivative to convert
     */
    calcUnderlyingValues(
      _derivative: PromiseOrValue<string>,
      _derivativeAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<
      [string[], BigNumber[]] & {
        underlyings_: string[];
        underlyingAmounts_: BigNumber[];
      }
    >;

    /**
     * Gets the `IBETH_TOKEN` variable
     */
    getIbethToken(overrides?: CallOverrides): Promise<string>;

    /**
     * Gets the `WETH_TOKEN` variable
     */
    getWethToken(overrides?: CallOverrides): Promise<string>;

    /**
     * Checks if an asset is supported by the price feed
     * @param _asset The asset to check
     */
    isSupportedAsset(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    /**
     * Converts a given amount of a derivative to its underlying asset values
     * @param _derivative The derivative to convert
     * @param _derivativeAmount The amount of the derivative to convert
     */
    calcUnderlyingValues(
      _derivative: PromiseOrValue<string>,
      _derivativeAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    /**
     * Gets the `IBETH_TOKEN` variable
     */
    getIbethToken(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Gets the `WETH_TOKEN` variable
     */
    getWethToken(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Checks if an asset is supported by the price feed
     * @param _asset The asset to check
     */
    isSupportedAsset(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Converts a given amount of a derivative to its underlying asset values
     * @param _derivative The derivative to convert
     * @param _derivativeAmount The amount of the derivative to convert
     */
    calcUnderlyingValues(
      _derivative: PromiseOrValue<string>,
      _derivativeAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    /**
     * Gets the `IBETH_TOKEN` variable
     */
    getIbethToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Gets the `WETH_TOKEN` variable
     */
    getWethToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Checks if an asset is supported by the price feed
     * @param _asset The asset to check
     */
    isSupportedAsset(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
