/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common';

export interface ZeroExV2AdapterInterface extends utils.Interface {
  functions: {
    'ADD_TRACKED_ASSETS_SELECTOR()': FunctionFragment;
    'APPROVE_ASSETS_SELECTOR()': FunctionFragment;
    'CLAIM_REWARDS_AND_REINVEST_SELECTOR()': FunctionFragment;
    'CLAIM_REWARDS_AND_SWAP_SELECTOR()': FunctionFragment;
    'CLAIM_REWARDS_SELECTOR()': FunctionFragment;
    'LEND_AND_STAKE_SELECTOR()': FunctionFragment;
    'LEND_SELECTOR()': FunctionFragment;
    'REDEEM_SELECTOR()': FunctionFragment;
    'REMOVE_TRACKED_ASSETS_SELECTOR()': FunctionFragment;
    'STAKE_SELECTOR()': FunctionFragment;
    'TAKE_ORDER_SELECTOR()': FunctionFragment;
    'UNSTAKE_AND_REDEEM_SELECTOR()': FunctionFragment;
    'UNSTAKE_SELECTOR()': FunctionFragment;
    'addAllowedMakers(address[])': FunctionFragment;
    'getExchange()': FunctionFragment;
    'getFundDeployer()': FunctionFragment;
    'getIntegrationManager()': FunctionFragment;
    'getOwner()': FunctionFragment;
    'identifier()': FunctionFragment;
    'isAllowedMaker(address)': FunctionFragment;
    'parseAssetsForMethod(bytes4,bytes)': FunctionFragment;
    'removeAllowedMakers(address[])': FunctionFragment;
    'takeOrder(address,bytes,bytes)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'ADD_TRACKED_ASSETS_SELECTOR'
      | 'APPROVE_ASSETS_SELECTOR'
      | 'CLAIM_REWARDS_AND_REINVEST_SELECTOR'
      | 'CLAIM_REWARDS_AND_SWAP_SELECTOR'
      | 'CLAIM_REWARDS_SELECTOR'
      | 'LEND_AND_STAKE_SELECTOR'
      | 'LEND_SELECTOR'
      | 'REDEEM_SELECTOR'
      | 'REMOVE_TRACKED_ASSETS_SELECTOR'
      | 'STAKE_SELECTOR'
      | 'TAKE_ORDER_SELECTOR'
      | 'UNSTAKE_AND_REDEEM_SELECTOR'
      | 'UNSTAKE_SELECTOR'
      | 'addAllowedMakers'
      | 'getExchange'
      | 'getFundDeployer'
      | 'getIntegrationManager'
      | 'getOwner'
      | 'identifier'
      | 'isAllowedMaker'
      | 'parseAssetsForMethod'
      | 'removeAllowedMakers'
      | 'takeOrder',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'ADD_TRACKED_ASSETS_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'APPROVE_ASSETS_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'CLAIM_REWARDS_AND_REINVEST_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'CLAIM_REWARDS_AND_SWAP_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'CLAIM_REWARDS_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'LEND_AND_STAKE_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'LEND_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'REDEEM_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'REMOVE_TRACKED_ASSETS_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'STAKE_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'TAKE_ORDER_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'UNSTAKE_AND_REDEEM_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'UNSTAKE_SELECTOR',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'addAllowedMakers',
    values: [PromiseOrValue<string>[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'getExchange',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getFundDeployer',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getIntegrationManager',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'getOwner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'identifier',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'isAllowedMaker',
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: 'parseAssetsForMethod',
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
  ): string;
  encodeFunctionData(
    functionFragment: 'removeAllowedMakers',
    values: [PromiseOrValue<string>[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'takeOrder',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
    ],
  ): string;

  decodeFunctionResult(
    functionFragment: 'ADD_TRACKED_ASSETS_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'APPROVE_ASSETS_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'CLAIM_REWARDS_AND_REINVEST_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'CLAIM_REWARDS_AND_SWAP_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'CLAIM_REWARDS_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'LEND_AND_STAKE_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'LEND_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'REDEEM_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'REMOVE_TRACKED_ASSETS_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'STAKE_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'TAKE_ORDER_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'UNSTAKE_AND_REDEEM_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'UNSTAKE_SELECTOR',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'addAllowedMakers',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getExchange',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getFundDeployer',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getIntegrationManager',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'identifier', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'isAllowedMaker',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'parseAssetsForMethod',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'removeAllowedMakers',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'takeOrder', data: BytesLike): Result;

  events: {
    'AllowedMakerAdded(address)': EventFragment;
    'AllowedMakerRemoved(address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'AllowedMakerAdded'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'AllowedMakerRemoved'): EventFragment;
}

export interface AllowedMakerAddedEventObject {
  account: string;
}
export type AllowedMakerAddedEvent = TypedEvent<
  [string],
  AllowedMakerAddedEventObject
>;

export type AllowedMakerAddedEventFilter =
  TypedEventFilter<AllowedMakerAddedEvent>;

export interface AllowedMakerRemovedEventObject {
  account: string;
}
export type AllowedMakerRemovedEvent = TypedEvent<
  [string],
  AllowedMakerRemovedEventObject
>;

export type AllowedMakerRemovedEventFilter =
  TypedEventFilter<AllowedMakerRemovedEvent>;

export interface ZeroExV2Adapter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ZeroExV2AdapterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ADD_TRACKED_ASSETS_SELECTOR(overrides?: CallOverrides): Promise<[string]>;

    APPROVE_ASSETS_SELECTOR(overrides?: CallOverrides): Promise<[string]>;

    CLAIM_REWARDS_AND_REINVEST_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<[string]>;

    CLAIM_REWARDS_AND_SWAP_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<[string]>;

    CLAIM_REWARDS_SELECTOR(overrides?: CallOverrides): Promise<[string]>;

    LEND_AND_STAKE_SELECTOR(overrides?: CallOverrides): Promise<[string]>;

    LEND_SELECTOR(overrides?: CallOverrides): Promise<[string]>;

    REDEEM_SELECTOR(overrides?: CallOverrides): Promise<[string]>;

    REMOVE_TRACKED_ASSETS_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<[string]>;

    STAKE_SELECTOR(overrides?: CallOverrides): Promise<[string]>;

    TAKE_ORDER_SELECTOR(overrides?: CallOverrides): Promise<[string]>;

    UNSTAKE_AND_REDEEM_SELECTOR(overrides?: CallOverrides): Promise<[string]>;

    UNSTAKE_SELECTOR(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Adds accounts to the list of allowed 0x order makers
     * @param _accountsToAdd Accounts to add
     */
    addAllowedMakers(
      _accountsToAdd: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    /**
     * Gets the `EXCHANGE` variable value
     */
    getExchange(
      overrides?: CallOverrides,
    ): Promise<[string] & { exchange_: string }>;

    /**
     * Gets the `FUND_DEPLOYER` variable
     */
    getFundDeployer(
      overrides?: CallOverrides,
    ): Promise<[string] & { fundDeployer_: string }>;

    /**
     * Gets the `INTEGRATION_MANAGER` variable
     */
    getIntegrationManager(
      overrides?: CallOverrides,
    ): Promise<[string] & { integrationManager_: string }>;

    /**
     * Ownership is deferred to the owner of the FundDeployer contract
     * Gets the owner of this contract
     */
    getOwner(overrides?: CallOverrides): Promise<[string] & { owner_: string }>;

    /**
     * Provides a constant string identifier for an adapter
     */
    identifier(
      overrides?: CallOverrides,
    ): Promise<[string] & { identifier_: string }>;

    /**
     * Checks whether an account is an allowed maker of 0x orders
     * @param _who The account to check
     */
    isAllowedMaker(
      _who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean] & { isAllowedMaker_: boolean }>;

    /**
     * Parses the expected assets to receive from a call on integration
     * @param _encodedCallArgs The encoded parameters for the callOnIntegration
     * @param _selector The function selector for the callOnIntegration
     */
    parseAssetsForMethod(
      _selector: PromiseOrValue<BytesLike>,
      _encodedCallArgs: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<
      [number, string[], BigNumber[], string[], BigNumber[]] & {
        spendAssetsHandleType_: number;
        spendAssets_: string[];
        spendAssetAmounts_: BigNumber[];
        incomingAssets_: string[];
        minIncomingAssetAmounts_: BigNumber[];
      }
    >;

    /**
     * Removes accounts from the list of allowed 0x order makers
     * @param _accountsToRemove Accounts to remove
     */
    removeAllowedMakers(
      _accountsToRemove: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    /**
     * Take an order on 0x
     * @param _encodedAssetTransferArgs Encoded args for expected assets to spend and receive
     * @param _encodedCallArgs Encoded order parameters
     * @param _vaultProxy The VaultProxy of the calling fund
     */
    takeOrder(
      _vaultProxy: PromiseOrValue<string>,
      _encodedCallArgs: PromiseOrValue<BytesLike>,
      _encodedAssetTransferArgs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;
  };

  ADD_TRACKED_ASSETS_SELECTOR(overrides?: CallOverrides): Promise<string>;

  APPROVE_ASSETS_SELECTOR(overrides?: CallOverrides): Promise<string>;

  CLAIM_REWARDS_AND_REINVEST_SELECTOR(
    overrides?: CallOverrides,
  ): Promise<string>;

  CLAIM_REWARDS_AND_SWAP_SELECTOR(overrides?: CallOverrides): Promise<string>;

  CLAIM_REWARDS_SELECTOR(overrides?: CallOverrides): Promise<string>;

  LEND_AND_STAKE_SELECTOR(overrides?: CallOverrides): Promise<string>;

  LEND_SELECTOR(overrides?: CallOverrides): Promise<string>;

  REDEEM_SELECTOR(overrides?: CallOverrides): Promise<string>;

  REMOVE_TRACKED_ASSETS_SELECTOR(overrides?: CallOverrides): Promise<string>;

  STAKE_SELECTOR(overrides?: CallOverrides): Promise<string>;

  TAKE_ORDER_SELECTOR(overrides?: CallOverrides): Promise<string>;

  UNSTAKE_AND_REDEEM_SELECTOR(overrides?: CallOverrides): Promise<string>;

  UNSTAKE_SELECTOR(overrides?: CallOverrides): Promise<string>;

  /**
   * Adds accounts to the list of allowed 0x order makers
   * @param _accountsToAdd Accounts to add
   */
  addAllowedMakers(
    _accountsToAdd: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  /**
   * Gets the `EXCHANGE` variable value
   */
  getExchange(overrides?: CallOverrides): Promise<string>;

  /**
   * Gets the `FUND_DEPLOYER` variable
   */
  getFundDeployer(overrides?: CallOverrides): Promise<string>;

  /**
   * Gets the `INTEGRATION_MANAGER` variable
   */
  getIntegrationManager(overrides?: CallOverrides): Promise<string>;

  /**
   * Ownership is deferred to the owner of the FundDeployer contract
   * Gets the owner of this contract
   */
  getOwner(overrides?: CallOverrides): Promise<string>;

  /**
   * Provides a constant string identifier for an adapter
   */
  identifier(overrides?: CallOverrides): Promise<string>;

  /**
   * Checks whether an account is an allowed maker of 0x orders
   * @param _who The account to check
   */
  isAllowedMaker(
    _who: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  /**
   * Parses the expected assets to receive from a call on integration
   * @param _encodedCallArgs The encoded parameters for the callOnIntegration
   * @param _selector The function selector for the callOnIntegration
   */
  parseAssetsForMethod(
    _selector: PromiseOrValue<BytesLike>,
    _encodedCallArgs: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides,
  ): Promise<
    [number, string[], BigNumber[], string[], BigNumber[]] & {
      spendAssetsHandleType_: number;
      spendAssets_: string[];
      spendAssetAmounts_: BigNumber[];
      incomingAssets_: string[];
      minIncomingAssetAmounts_: BigNumber[];
    }
  >;

  /**
   * Removes accounts from the list of allowed 0x order makers
   * @param _accountsToRemove Accounts to remove
   */
  removeAllowedMakers(
    _accountsToRemove: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  /**
   * Take an order on 0x
   * @param _encodedAssetTransferArgs Encoded args for expected assets to spend and receive
   * @param _encodedCallArgs Encoded order parameters
   * @param _vaultProxy The VaultProxy of the calling fund
   */
  takeOrder(
    _vaultProxy: PromiseOrValue<string>,
    _encodedCallArgs: PromiseOrValue<BytesLike>,
    _encodedAssetTransferArgs: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    ADD_TRACKED_ASSETS_SELECTOR(overrides?: CallOverrides): Promise<string>;

    APPROVE_ASSETS_SELECTOR(overrides?: CallOverrides): Promise<string>;

    CLAIM_REWARDS_AND_REINVEST_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<string>;

    CLAIM_REWARDS_AND_SWAP_SELECTOR(overrides?: CallOverrides): Promise<string>;

    CLAIM_REWARDS_SELECTOR(overrides?: CallOverrides): Promise<string>;

    LEND_AND_STAKE_SELECTOR(overrides?: CallOverrides): Promise<string>;

    LEND_SELECTOR(overrides?: CallOverrides): Promise<string>;

    REDEEM_SELECTOR(overrides?: CallOverrides): Promise<string>;

    REMOVE_TRACKED_ASSETS_SELECTOR(overrides?: CallOverrides): Promise<string>;

    STAKE_SELECTOR(overrides?: CallOverrides): Promise<string>;

    TAKE_ORDER_SELECTOR(overrides?: CallOverrides): Promise<string>;

    UNSTAKE_AND_REDEEM_SELECTOR(overrides?: CallOverrides): Promise<string>;

    UNSTAKE_SELECTOR(overrides?: CallOverrides): Promise<string>;

    /**
     * Adds accounts to the list of allowed 0x order makers
     * @param _accountsToAdd Accounts to add
     */
    addAllowedMakers(
      _accountsToAdd: PromiseOrValue<string>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    /**
     * Gets the `EXCHANGE` variable value
     */
    getExchange(overrides?: CallOverrides): Promise<string>;

    /**
     * Gets the `FUND_DEPLOYER` variable
     */
    getFundDeployer(overrides?: CallOverrides): Promise<string>;

    /**
     * Gets the `INTEGRATION_MANAGER` variable
     */
    getIntegrationManager(overrides?: CallOverrides): Promise<string>;

    /**
     * Ownership is deferred to the owner of the FundDeployer contract
     * Gets the owner of this contract
     */
    getOwner(overrides?: CallOverrides): Promise<string>;

    /**
     * Provides a constant string identifier for an adapter
     */
    identifier(overrides?: CallOverrides): Promise<string>;

    /**
     * Checks whether an account is an allowed maker of 0x orders
     * @param _who The account to check
     */
    isAllowedMaker(
      _who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    /**
     * Parses the expected assets to receive from a call on integration
     * @param _encodedCallArgs The encoded parameters for the callOnIntegration
     * @param _selector The function selector for the callOnIntegration
     */
    parseAssetsForMethod(
      _selector: PromiseOrValue<BytesLike>,
      _encodedCallArgs: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<
      [number, string[], BigNumber[], string[], BigNumber[]] & {
        spendAssetsHandleType_: number;
        spendAssets_: string[];
        spendAssetAmounts_: BigNumber[];
        incomingAssets_: string[];
        minIncomingAssetAmounts_: BigNumber[];
      }
    >;

    /**
     * Removes accounts from the list of allowed 0x order makers
     * @param _accountsToRemove Accounts to remove
     */
    removeAllowedMakers(
      _accountsToRemove: PromiseOrValue<string>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    /**
     * Take an order on 0x
     * @param _encodedAssetTransferArgs Encoded args for expected assets to spend and receive
     * @param _encodedCallArgs Encoded order parameters
     * @param _vaultProxy The VaultProxy of the calling fund
     */
    takeOrder(
      _vaultProxy: PromiseOrValue<string>,
      _encodedCallArgs: PromiseOrValue<BytesLike>,
      _encodedAssetTransferArgs: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<void>;
  };

  filters: {
    'AllowedMakerAdded(address)'(
      account?: PromiseOrValue<string> | null,
    ): AllowedMakerAddedEventFilter;
    AllowedMakerAdded(
      account?: PromiseOrValue<string> | null,
    ): AllowedMakerAddedEventFilter;

    'AllowedMakerRemoved(address)'(
      account?: PromiseOrValue<string> | null,
    ): AllowedMakerRemovedEventFilter;
    AllowedMakerRemoved(
      account?: PromiseOrValue<string> | null,
    ): AllowedMakerRemovedEventFilter;
  };

  estimateGas: {
    ADD_TRACKED_ASSETS_SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    APPROVE_ASSETS_SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    CLAIM_REWARDS_AND_REINVEST_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    CLAIM_REWARDS_AND_SWAP_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    CLAIM_REWARDS_SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    LEND_AND_STAKE_SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    LEND_SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    REDEEM_SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    REMOVE_TRACKED_ASSETS_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    STAKE_SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    TAKE_ORDER_SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    UNSTAKE_AND_REDEEM_SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    UNSTAKE_SELECTOR(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Adds accounts to the list of allowed 0x order makers
     * @param _accountsToAdd Accounts to add
     */
    addAllowedMakers(
      _accountsToAdd: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    /**
     * Gets the `EXCHANGE` variable value
     */
    getExchange(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Gets the `FUND_DEPLOYER` variable
     */
    getFundDeployer(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Gets the `INTEGRATION_MANAGER` variable
     */
    getIntegrationManager(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Ownership is deferred to the owner of the FundDeployer contract
     * Gets the owner of this contract
     */
    getOwner(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Provides a constant string identifier for an adapter
     */
    identifier(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Checks whether an account is an allowed maker of 0x orders
     * @param _who The account to check
     */
    isAllowedMaker(
      _who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    /**
     * Parses the expected assets to receive from a call on integration
     * @param _encodedCallArgs The encoded parameters for the callOnIntegration
     * @param _selector The function selector for the callOnIntegration
     */
    parseAssetsForMethod(
      _selector: PromiseOrValue<BytesLike>,
      _encodedCallArgs: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    /**
     * Removes accounts from the list of allowed 0x order makers
     * @param _accountsToRemove Accounts to remove
     */
    removeAllowedMakers(
      _accountsToRemove: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    /**
     * Take an order on 0x
     * @param _encodedAssetTransferArgs Encoded args for expected assets to spend and receive
     * @param _encodedCallArgs Encoded order parameters
     * @param _vaultProxy The VaultProxy of the calling fund
     */
    takeOrder(
      _vaultProxy: PromiseOrValue<string>,
      _encodedCallArgs: PromiseOrValue<BytesLike>,
      _encodedAssetTransferArgs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ADD_TRACKED_ASSETS_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    APPROVE_ASSETS_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    CLAIM_REWARDS_AND_REINVEST_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    CLAIM_REWARDS_AND_SWAP_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    CLAIM_REWARDS_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    LEND_AND_STAKE_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    LEND_SELECTOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REDEEM_SELECTOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REMOVE_TRACKED_ASSETS_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    STAKE_SELECTOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TAKE_ORDER_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    UNSTAKE_AND_REDEEM_SELECTOR(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    UNSTAKE_SELECTOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Adds accounts to the list of allowed 0x order makers
     * @param _accountsToAdd Accounts to add
     */
    addAllowedMakers(
      _accountsToAdd: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    /**
     * Gets the `EXCHANGE` variable value
     */
    getExchange(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Gets the `FUND_DEPLOYER` variable
     */
    getFundDeployer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Gets the `INTEGRATION_MANAGER` variable
     */
    getIntegrationManager(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    /**
     * Ownership is deferred to the owner of the FundDeployer contract
     * Gets the owner of this contract
     */
    getOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Provides a constant string identifier for an adapter
     */
    identifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Checks whether an account is an allowed maker of 0x orders
     * @param _who The account to check
     */
    isAllowedMaker(
      _who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    /**
     * Parses the expected assets to receive from a call on integration
     * @param _encodedCallArgs The encoded parameters for the callOnIntegration
     * @param _selector The function selector for the callOnIntegration
     */
    parseAssetsForMethod(
      _selector: PromiseOrValue<BytesLike>,
      _encodedCallArgs: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    /**
     * Removes accounts from the list of allowed 0x order makers
     * @param _accountsToRemove Accounts to remove
     */
    removeAllowedMakers(
      _accountsToRemove: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    /**
     * Take an order on 0x
     * @param _encodedAssetTransferArgs Encoded args for expected assets to spend and receive
     * @param _encodedCallArgs Encoded order parameters
     * @param _vaultProxy The VaultProxy of the calling fund
     */
    takeOrder(
      _vaultProxy: PromiseOrValue<string>,
      _encodedCallArgs: PromiseOrValue<BytesLike>,
      _encodedAssetTransferArgs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;
  };
}
